### ISSUE TITLE
Setting to enable per forum, first post or reply basis

### ISSUE THREAD

**Issue by Sama34** [mybbgroup/Link-tools#1]
I would like to suggest a way to somehow enable the plugin only for specific forums, as well as to save and render links only for the first post, replies, or both :)

**Comment by lairdshaw** [comment]
I like your suggestion! I'll look into it, unless you want to do that first and submit a PR. Am trying to focus on reviewing core PRs for the next little while so I won't get onto this suggestion immediately, but it does seem worth implementing.
