### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by wezlol** [mybbgroup/Link-tools#2]
Issue: When I visit some topics of my forum I get a blank screen and 'HTTP ERROR 500'.
Example url: https://m4tr1x.online/forum/showthread.php?tid=68&pid=114

Extra information: Other threads/pages work fine.
Example url: https://m4tr1x.online/forum/showthread.php?tid=103

Admin CP>Configuration>Plugins>
![image](https://github.com/mybbgroup/Link-tools/assets/35075726/d8d768af-adcb-4845-a3be-34675c3848b9)
```
Checking whether the cURL extension is loaded...PASS
Checking for the existence of the curl_init() function...PASS
Checking for the successful functioning of single-page, HTTP (non-secure) cURL downloads...PASS
Checking for the successful functioning of single-page, HTTPS (secure) cURL downloads...PASS
```
from: lkt-curl-functionality-checker.php

_**Hosting from: https://infinityfree.net/**_

![image](https://github.com/mybbgroup/Link-tools/assets/35075726/52550887-efcd-4c4c-a18b-17acebcdc603)

_**edited with more information**_

**Comment by wezlol** [comment]
update: I am using a free host / asking the host now

**Comment by lairdshaw** [comment]
> update: I am using a free host / asking the host now

No worries, let us know if/when you can identify the error more specifically.

**Comment by wezlol** [comment]
I've contacted the host and was able to repair another plugin that displayed the 500 error. However, with this plugin I get these errors:
![image](https://github.com/mybbgroup/Link-tools/assets/35075726/b0b9981d-0832-47e5-bd3a-29d9360fa572)
When I click on it I get: (/forum/admin/index.php?module=tools-recount_rebuild)
HTTP ERROR 500

including all threads containing these links

**Comment by lairdshaw** [comment]
Unfortunately, without the exact error message, there's not enough to go on (but it *does* appear that the 500 error is being caused by Link Tools). Can you ask your host to look in the server logs and share with you the error message that accompanies the 500 return?

**Comment by lairdshaw** [comment]
> 4x PASS in the test php.

Just to follow up on this, I presume you mean `lkt-curl-functionality-checker.php` rather than `test.php`.

You should have gotten six passes rather than just four. Can you confirm that you only got four instead of six?

**Comment by lairdshaw** [comment]
@wezlol please let us know where you're at with this. If you don't respond, I'll assume that this issue can be closed.

**Comment by wezlol** [comment]
I am getting this:
```
Checking whether the cURL extension is loaded...PASS

Checking for the existence of the curl_init() function...PASS

Checking for the successful functioning of single-page, HTTP (non-secure) cURL downloads...PASS

Checking for the successful functioning of single-page, HTTPS (secure) cURL downloads...PASS

Checking for the successful functioning of multi-page, HTTP (non-secure) cURL downloads...
```
--

edit: I am changing my SSL certificate now to see if that works
edit2: didnt help

**Comment by wezlol** [comment]
I have enabled PHP debugging and got this:
`Fatal error: Uncaught Error: Call to undefined function curl_multi_exec() in /home/vol14_5/epizy.com/epiz_33699107/m4tr1x.2kool4u.net/htdocs/forum/inc/plugins/linktools.php:1665 Stack trace: #0 /home/vol14_5/epizy.com/epiz_33699107/m4tr1x.2kool4u.net/htdocs/forum/inc/plugins/linktools.php(2485): lkt_get_url_redirs(Array, Array, Array, false, true, true, true) #1 /home/vol14_5/epizy.com/epiz_33699107/m4tr1x.2kool4u.net/htdocs/forum/inc/plugins/linktools.php(3033): lkt_get_url_term_redirs(Array, NULL) #2 /home/vol14_5/epizy.com/epiz_33699107/m4tr1x.2kool4u.net/htdocs/forum/inc/plugins/linktools.php(3150): lkt_get_and_store_terms(30, 489) #3 /home/vol14_5/epizy.com/epiz_33699107/m4tr1x.2kool4u.net/htdocs/forum/inc/class_plugins.php(142): lkt_hookin__admin_tools_recount_rebuild('') #4 /home/vol14_5/epizy.com/epiz_33699107/m4tr1x.2kool4u.net/htdocs/forum/admin/modules/tools/recount_rebuild.php(19): pluginSystem->run_hooks(Array) #5 /home/vol14_5/epizy.com/epiz_33699107/m4tr1x.2kool4u.net/htdocs/forum/admin/index.php(830): require('/home/vol14_5/e...') #6 {main} thrown in /home/vol14_5/epizy.com/epiz_33699107/m4tr1x.2kool4u.net/htdocs/forum/inc/plugins/linktools.php on line 1665`

**Comment by lairdshaw** [comment]
The problem is that the `curl_multi_exec()` function is not available. This is a built-in PHP function, and is part of the [Client URL Library (cURL)](https://www.php.net/manual/en/book.curl.php). Other cURL PHP functions seem to be available given that the first four tests pass, so, presumably, your web host has selectively disabled this one. Check with them to see whether they'll enable it for you.

**Comment by lairdshaw** [comment]
@wezlol, again: please let us know where you're at with this. If you don't respond, I'll assume that this issue can be closed.

**Comment by lairdshaw** [comment]
Closing due to lack of response. Feel free to reopen again if/when you return, @wezlol.
